# permissions for end users to view webhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-viewer-role
rules:
- apiGroups:
  - webhook.freshlist.us
  resources:
  - webhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webhook.freshlist.us
  resources:
  - webhooks/status
  verbs:
  - get
