name: Build/Push Action
on: [push]
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: freshlist-v1
  GKE_ZONE: us-east1-b 
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  # unit-test:
  #   name: unit-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2

  #     - name: Unit Test Frontend
  #       run: | 
  #         cd frontend;
  #         yarn -s;
  #         yarn run test;
  #         echo "Exited with '$?'"

  # static-code-analysis:
  #   needs: unit-test
  #   name: static-code-analysis
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2

  #     - name: Analyze Frontend
  #       run: | 
  #         cd frontend;
  #         yarn -s;
  #         # necessary to collect coverage
  #         yarn run coverage;
  #         node sonarqube-scanner.js

  setup-build-push-deploy:
    needs: static-code-analysis
    name: test-push-build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

    # NEW
      - name: Set up Kustomize
        run: |-
          curl --location https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.2.0/kustomize_v4.2.0_linux_amd64.tar.gz | tar xz
          chmod u+x ./kustomize

      # NEW
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
              # Get the GKE credentials so we can deploy to the cluster

      # NEW
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push UI
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: cmwylie19/webhook-frontend:latest

      - name: Deploy UI
        run: |-
          kubectl apply -f ./frontend/k8s
          kubectl rollout restart deploy/frontend


      # - name: Build and push Agenda
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./agenda
      #     push: true
      #     tags: cmwylie19/agenda:latest

      # - name: Build and push Auth
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./auth
      #     push: true
      #     tags: cmwylie19/auth:latest

      # - name: Build and push Place
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./place
      #     push: true
      #     tags: cmwylie19/place:latest     

      # - name: Deploy Agenda
      #   run: |-
      #     kubectl apply -f ./agenda/k8s
      #     kubectl rollout restart deploy/agenda          

      # - name: Deploy Place
      #   run: |-
      #     kubectl apply -f ./place/k8s
      #     kubectl rollout restart deploy/place

      # - name: Deploy Auth
      #   run: |-
      #     kubectl apply -f ./auth/k8s
      #     kubectl rollout restart deploy/auth

      - run: echo "🍏 This job's status is ${{ job.status }}."